time:
  handler: CalculateTimeParamHandler
path_length:
  handler: CalculatePathLengthParamHandler
distance:
  handler: CalculateDistanceParamHandler
resource_cpu:
  handler: CalculateResourcesCpuParamHandler
resource_mem:
  handler: CalculateResourcesMemParamHandler
resource_io:
  handler: CalculateResourcesIOParamHandler
resource_network:
  handler: CalculateResourcesNetworkParamHandler
obstacle_distance:
  handler: CalculateDistanceToObstaclesParamHandler
publish_rate:
  handler: CalculatePublishRateParamHandler
interface:
  handler: CalculateInterfaceParamHandler
localization:
  handler: CheckLocalizationParamHandler
localization_distance:
  handler: CalculateLocalizationDistanceParamHandler
# example:
#   handler: ExampleParamHandler